/****** Object:  Database [MSCSC]    Script Date: 2019/12/8 10:19:25 ******/
CREATE DATABASE [MSCSC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MSCSC_DATA', FILENAME = N'E:\Microsoft SQL Server\DATA\MSCSC.mdf' , SIZE = 8192KB , MAXSIZE = 20480KB , FILEGROWTH = 10%),
( NAME = N'MSCSC_DATA_2', FILENAME = N'E:\Microsoft SQL Server\DATA\MSCSC2.ndf' , SIZE = 5120KB , MAXSIZE = 10240KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'学生管理系统_LOG', FILENAME = N'E:\Microsoft SQL Server\LOG\MSCSC.ldf' , SIZE = 8192KB , MAXSIZE = 20480KB , FILEGROWTH = 5%)
GO


